[book]
title = "Rust Up Algorithms"
authors = ["Jay Jang"]
language = "en"


[output.html]
default-theme = "latte"
preferred-dark-theme = "mocha"
smart-punctuation = false
git-repository-url = "https://github.com/boba-jjang/rust-up-algorithms"
edit-url-template = "https://github.com/boba-jjang/rust-up-algorithms/edit/main/book/src/{path}"
additional-css = ["./theme/catppuccin.css"]

[output.html.fold]
enable = true
level = 0

[preprocessor.embedify]
footer.enable = true
footer.message = "Copyright © 2026 • Created by [Jay Jang](https://jwj.fyi/)"
